services:
  carwebapi:
    build:
      context: ./CarWebAPI
      dockerfile: Dockerfile
    container_name: carwebapi
    ports:
      - "5219:5219"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - CarSelectionDatabase__ConnectionString=mongodb://mongodb:27017
      - CarSelectionDatabase__DatabaseName=CarSelection
      - CarSelectionDatabase__CarsCollectionName=Cars
      - RedisCacheOptions__Configuration=redis:6379
      - RedisCacheOptions__InstanceName=CarSelection_
    depends_on:
      - mongodb
      - redis
    networks:
      - monitoring


  userapi:
    build: 
      context: ./UserWebAPI
      dockerfile: Dockerfile
    container_name: userapi
    ports:
      - "5220:5220"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - UsersDatabase__ConnectionString=mongodb://mongodb:27017
      - UsersDatabase__DatabaseName=Users
      - UsersDatabase__UsersCollectionName=Users
    depends_on:
      - mongodb
      - redis
    networks:
      - monitoring


  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - monitoring


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring


  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  mongo_data:
  grafana_data: