{
 "title": "Cars_Dashboard",
 "description": "Dashboard for CarWebAPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime_Panel",
   "type": "timeseries",
   "description": "Panel for uptime visualization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS_Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "requests_per_second_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency_bucket_panel",
   "type": "barchart",
   "description": "Visualization for latency bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "request_latency_second_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency_count_panel",
   "type": "timeseries",
   "description": "Visualization for latency panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "request_latency_second_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency_sum_panel",
   "type": "timeseries",
   "description": "Visualization for latency sum",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "request_latency_second_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors_panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "errors_total", "legendFormat": "__auto" }
   ]
  }
 ]
}